### ISSUE TITLE
RIPE API (Python) Tech Debt

### ISSUE THREAD

**Issue by dsafonso** [ripe-tech/ripe-api#30]
# Rationale

RIPE API hasn't been updated as much as RIPE SDK, so we must catch up on that debt.

# Description

- Find out what endpoints are missing
- Implement the missing endpoints
- Update the Changelog

## Estimation

| Discipline | Estimation |
| --- | --- |
| **Software Development + QA** | 4 days |

**Comment by joamag** [comment]
This is now considered done
